ALTER TABLE consumption.dashboard_market_overview
    ADD COLUMN IF NOT EXISTS change_1d NUMERIC,
    ADD COLUMN IF NOT EXISTS change_1w NUMERIC,
    ADD COLUMN IF NOT EXISTS change_1m NUMERIC,
    ADD COLUMN IF NOT EXISTS change_ytd NUMERIC,
    ADD COLUMN IF NOT EXISTS est_1d VARCHAR(20),
    ADD COLUMN IF NOT EXISTS est_1w VARCHAR(20),
    ADD COLUMN IF NOT EXISTS est_1m VARCHAR(20);
