#!/usr/bin/env python3
"""
register_strategy.py — CLI to onboard a new trading strategy.

Replaces the previous 3-file manual edit (strategies/run_signals.py imports,
strategies/stubs.py classes, regime/regime_rules.py::STRATEGY_MAP) with one
command:

    python3 strategies/register_strategy.py \
        --id 21 \
        --name "Crypto vol carry" \
        --regime CARRY \
        --asset-class crypto \
        --class-name Strategy21 \
        --module strategies.crypto.strategy_21

What it does (in order, atomically):
  1. Validates the new entry against registry.json (no id collision, no
     class_path collision, regime + asset_class allow-listed).
  2. Creates a stub strategy class file from a template — only if it
     doesn't already exist.
  3. Appends the entry to registry.json with enabled=false (so the
     daily cron doesn't pick up a half-baked implementation by accident).
  4. Prints next steps + a `git diff` hint.

After the operator implements compute_signal() in the new file, they
flip enabled=true in registry.json. No cron restart needed; the next
30-min cycle will load it dynamically.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(HERE, "registry.json")

VALID_REGIMES = {"TREND", "MEAN_REV", "CARRY", "EVENT", "FLAT"}
VALID_ASSET_CLASSES = {"equity", "crypto", "fx", "commodity"}


STRATEGY_TEMPLATE = '''#!/usr/bin/env python3
"""
S-{id:02d}: {name}
Generated by register_strategy.py at {timestamp}.

TODO: implement compute_signal(). Until enabled=true in registry.json,
this class is loaded for validation but its signals are NOT written to DB.
"""

import sys
import os

# Signal-agent layout (post 2026-06-22 split):
#   agents/signals/strategies/<regime>/strategy_NN.py  ← this file
#   agents/etl/shared/scripts/db.py                     ← canonical DB pool
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SIGNALS_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
ETL_SHARED = os.path.normpath(os.path.join(SIGNALS_ROOT, '..', 'etl', 'shared', 'scripts'))
sys.path.insert(0, SIGNALS_ROOT)
sys.path.insert(0, ETL_SHARED)
os.environ.setdefault('AWS_REGION', 'ap-southeast-1')

from strategies.base_strategy import BaseStrategy


class {class_name}(BaseStrategy):
    def __init__(self, conn):
        super().__init__(conn, {id}, "{name}")

    def compute_signal(self) -> int:
        # Returns +1 (long), -1 (short), or 0 (flat).
        # MUST call is_active_today() first and return 0 if False.
        if not self.is_active_today():
            return 0

        # TODO: real signal logic here.
        return 0
'''


def _load_registry() -> Dict[str, Any]:
    with open(REGISTRY_PATH) as f:
        return json.load(f)


def _save_registry(data: Dict[str, Any]) -> None:
    # Stable-key ordering for clean diffs.
    with open(REGISTRY_PATH, "w") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")


def _class_path_to_file(module_path: str) -> str:
    """strategies.trend.strategy_21 → agents/signals/strategies/trend/strategy_21.py"""
    parts = module_path.split(".")
    if parts[0] != "strategies":
        raise SystemExit(
            f"module path must start with 'strategies.', got {module_path!r}"
        )
    workspace = os.path.normpath(os.path.join(HERE, ".."))
    return os.path.join(workspace, *parts) + ".py"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--id", type=int, required=True,
                   help="Numeric strategy id (must be unique)")
    p.add_argument("--name", required=True, help="Human-readable name")
    p.add_argument("--regime", required=True, choices=sorted(VALID_REGIMES),
                   help="Regime this strategy is active in")
    p.add_argument("--asset-class", required=True, choices=sorted(VALID_ASSET_CLASSES),
                   help="Asset class (used for filtering & reporting)")
    p.add_argument("--module", required=True,
                   help="Module path, e.g. strategies.trend.strategy_21")
    p.add_argument("--class-name", required=True,
                   help="Class name, e.g. Strategy21")
    p.add_argument("--enabled", action="store_true",
                   help="Set enabled=true (default: false until you implement)")
    p.add_argument("--notes", default="", help="Optional notes for the registry")
    p.add_argument("--force", action="store_true",
                   help="Overwrite an existing strategy file (DANGEROUS)")
    args = p.parse_args()

    # Load and validate against existing registry.
    data = _load_registry()
    existing = data.get("strategies", [])
    by_id = {e["id"]: e for e in existing}
    by_class_path = {e["class_path"]: e for e in existing}

    if args.id in by_id:
        sys.exit(f"FATAL: strategy id={args.id} already exists "
                 f"({by_id[args.id]['name']!r}). Pick another id.")

    class_path = f"{args.module}:{args.class_name}"
    if class_path in by_class_path:
        sys.exit(f"FATAL: class_path {class_path!r} already registered "
                 f"(id={by_class_path[class_path]['id']}).")

    # 2. Create the stub file (skip if it already exists unless --force).
    target_file = _class_path_to_file(args.module)
    os.makedirs(os.path.dirname(target_file), exist_ok=True)

    if os.path.exists(target_file) and not args.force:
        print(f"  Strategy file already exists at {target_file} — leaving as-is.")
    else:
        rendered = STRATEGY_TEMPLATE.format(
            id=args.id,
            class_name=args.class_name,
            name=args.name,
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
        with open(target_file, "w") as f:
            f.write(rendered)
        print(f"  Created {target_file}")

    # 3. Append to registry.
    new_entry = {
        "id": args.id,
        "name": args.name,
        "class_path": class_path,
        "regime": args.regime,
        "enabled": bool(args.enabled),
        "asset_class": args.asset_class,
        "params": {},
        "notes": args.notes or f"Registered {datetime.now(timezone.utc).date().isoformat()} via register_strategy.py. Implement compute_signal() then flip enabled=true.",
    }
    existing.append(new_entry)
    existing.sort(key=lambda e: e["id"])
    data["strategies"] = existing
    _save_registry(data)
    print(f"  Appended id={args.id} to {REGISTRY_PATH} (enabled={args.enabled})")

    # 4. Next steps.
    print(f"\nNext steps:")
    print(f"  1. Edit {target_file} → implement compute_signal()")
    print(f"  2. Run: python3 -m strategies.registry_loader  (validates registry)")
    print(f"  3. Flip enabled=true in registry.json once tested")
    print(f"  4. Commit: git add strategies/registry.json {target_file}")
    print(f"\nNo cron restart needed — daily_refresh.sh discovers it dynamically.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
