#!/usr/bin/env python3
"""
gen_strategy_docs.py — generate a docs/strategies/<strategy_id>.md for every
strategy in gold.strategy_registry that doesn't already have an AUTHORED doc.

The generated doc is filled from the registry (name, asset_class, status,
priority, execution_mode, universe_tickers, signal_logic, exit_logic,
signal_file_path), the strategy's criteria rows (gold.strategy_signal_criteria),
and its latest OOS run (gold.strategy_backtest_runs). Because it is generated
from data it cannot drift from the DB.

Rules:
  - If docs/strategies/<id>.md exists and is marked `source: authored`, skip it
    (a human owns that one — its logic lives in code, not data).
  - Otherwise (re)write it as `source: generated`.

Needs DB access. Run after onboarding a strategy:
    python3 tools/gen_strategy_docs.py            # write/refresh all generated docs
    python3 tools/gen_strategy_docs.py --check    # exit 1 if any would change (CI-in-DB)
"""
import argparse
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, ".."))
_DOCS = os.path.join(_REPO, "docs", "strategies")
sys.path.insert(0, os.path.join(_REPO, "agents", "etl", "shared", "scripts"))
os.environ.setdefault("AWS_REGION", "ap-southeast-1")


def _authored(path):
    if not os.path.isfile(path):
        return False
    with open(path) as f:
        head = f.read(200)
    return "source: authored" in head


def _mechanism(reg, criteria_ids, sid):
    if reg.get("signal_file_path"):
        return f"ingested(`{reg['signal_file_path']}`)"
    if sid in criteria_ids:
        return "criteria(`gold.strategy_signal_criteria`)"
    return "computed (see registry.signal_logic / a dedicated calculator)"


def render(reg, crit_rows, run, criteria_ids):
    sid = reg["strategy_id"]
    univ = reg.get("universe_tickers") or []
    lines = []
    lines.append("<!-- source: generated by tools/gen_strategy_docs.py — edit the prose,")
    lines.append("     but re-running the generator refreshes the data blocks. To take full")
    lines.append("     manual ownership, change the marker to `source: authored`. -->")
    lines.append(f"# {reg.get('name') or sid}\n")
    lines.append("| field | value |")
    lines.append("|---|---|")
    lines.append(f"| **strategy_id** | `{sid}` |")
    lines.append(f"| **status** | {reg.get('status')} |")
    lines.append(f"| **tier / priority** | {reg.get('priority')} |")
    lines.append(f"| **asset class** | {reg.get('asset_class')} |")
    lines.append(f"| **execution mode** | {reg.get('execution_mode')} |")
    lines.append(f"| **signal mechanism** | {_mechanism(reg, criteria_ids, sid)} |")
    lines.append(f"| **frequency** | {reg.get('frequency')} |")
    lines.append(f"| **universe size** | {len(univ)} |\n")

    lines.append("## Overview")
    lines.append((reg.get("signal_logic") or "_TODO: describe the edge / thesis. "
                  "registry.signal_logic is empty for this strategy._") + "\n")

    lines.append("## Universe")
    if univ:
        lines.append("`" + "`, `".join(univ) + "`\n")
    else:
        lines.append("_No universe_tickers in gold.strategy_registry — the strategy "
                     "will score/trade nothing until a universe is set._\n")

    lines.append("## Buy-signal pipeline")
    if crit_rows:
        lines.append("Evaluated by `build_strategy_scores.py` from "
                     "`gold.strategy_signal_criteria` (BUY when the logic_mode is satisfied):\n")
        lines.append("| criterion | operator | threshold | signal_type | logic_mode |")
        lines.append("|---|---|---|---|---|")
        for c in crit_rows:
            lines.append(f"| `{c['criterion_name']}` | {c['operator']} | {c['threshold']} "
                         f"| {c['signal_type']} | {c['logic_mode']} |")
        lines.append("")
    elif reg.get("signal_file_path"):
        lines.append(f"Signals are ingested from `{reg['signal_file_path']}` via "
                     "`ingest_paper_signal.py` into `gold.strategy_ticker_scores` "
                     "(score 100 = BUY per ticker in the file). The BUY logic itself "
                     "lives in whatever qr_research process writes that file — document it "
                     "here once known.\n")
    else:
        lines.append("_No criteria rows and no signal file. This strategy has NO wired "
                     "signal mechanism — it will show all-HOLD. Add criteria, a signal "
                     "file, or a dedicated calculator, then document the exact rule here._\n")

    lines.append("## Exit logic")
    lines.append((reg.get("exit_logic") or "_TODO: registry.exit_logic is empty._") + "\n")

    lines.append("## Backtest summary (OOS)")
    if run:
        lines.append(f"Latest `gold.strategy_backtest_runs` (run #{run.get('run_number')}, "
                     f"OOS {run.get('oos_start')}..{run.get('oos_end')}):")
        lines.append(f"- Sharpe: {run.get('sharpe_oos')}  ·  win rate: {run.get('win_rate_oos')}  "
                     f"·  max DD: {run.get('max_drawdown_oos')}")
        lines.append(f"- trades: {run.get('trade_count_oos')}  ·  profit factor: "
                     f"{run.get('profit_factor_oos')}  ·  gates passed: {run.get('all_risk_gates_passed')}\n")
    else:
        lines.append("_No backtest_runs row — OOS stats show '—' on the frontend "
                     "(honest empty state)._\n")

    lines.append("## Known issues / TODO")
    lines.append("_Generated stub — enrich with the real thesis and any wiring caveats._")
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="exit 1 if any generated doc is missing or out of date")
    args = p.parse_args()

    from db import get_connection
    os.makedirs(_DOCS, exist_ok=True)
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("""
        SELECT strategy_id, name, asset_class, status, priority, execution_mode,
               frequency, universe_tickers, signal_logic, exit_logic, signal_file_path
        FROM gold.strategy_registry WHERE retired_at IS NULL ORDER BY strategy_id
    """)
    cols = [d[0] for d in cur.description]
    regs = [dict(zip(cols, r)) for r in cur.fetchall()]

    cur.execute("SELECT DISTINCT strategy_id FROM gold.strategy_signal_criteria")
    criteria_ids = {r[0] for r in cur.fetchall()}

    def crit_for(sid):
        cur.execute("""SELECT criterion_name, operator, threshold, signal_type, logic_mode
                       FROM gold.strategy_signal_criteria WHERE strategy_id=%s
                       ORDER BY id""", (sid,))
        cc = [d[0] for d in cur.description]
        return [dict(zip(cc, r)) for r in cur.fetchall()]

    def run_for(sid):
        cur.execute("""SELECT run_number, oos_start, oos_end, sharpe_oos, win_rate_oos,
                              max_drawdown_oos, trade_count_oos, profit_factor_oos,
                              all_risk_gates_passed
                       FROM gold.strategy_backtest_runs WHERE strategy_id=%s
                       ORDER BY run_number DESC, created_at DESC LIMIT 1""", (sid,))
        row = cur.fetchone()
        if not row:
            return None
        return dict(zip([d[0] for d in cur.description], row))

    changed = 0
    for reg in regs:
        sid = reg["strategy_id"]
        path = os.path.join(_DOCS, f"{sid}.md")
        if _authored(path):
            continue
        new = render(reg, crit_for(sid), run_for(sid), criteria_ids)
        old = open(path).read() if os.path.isfile(path) else None
        if old != new:
            changed += 1
            if not args.check:
                with open(path, "w") as f:
                    f.write(new)
                print(f"  wrote docs/strategies/{sid}.md")
            else:
                print(f"  OUT OF DATE: docs/strategies/{sid}.md")

    conn.close()
    if args.check and changed:
        print(f"❌ {changed} generated strategy doc(s) missing/out of date — run gen_strategy_docs.py")
        return 1
    print(f"✅ strategy docs: {len(regs)} strategies, {changed} generated docs {'to write' if args.check else 'written'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
